### ISSUE TITLE
Can't install pyonfido through pip

### ISSUE THREAD

**Issue by Gorbyy** [smcl/pyonfido#10]
Trying the command `pip install pyonfido` raised the following error:
```
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-60TLCQ/pyonfido/
```

I was able to install the library through this:
```
$ git clone https://github.com/smcl/pyonfido.git
$ cd pyonfido
$ python setup.py install
```

**Comment by hjheath** [comment]
What version of Python are you using? I can install it for both 2.7 and 3.5

**Comment by Gorbyy** [comment]
I have Python 2.7.10

**Comment by Gorbyy** [comment]
Apparently I could perform `pip install pyonfido` after doing this:
```
$ git clone https://github.com/smcl/pyonfido.git
$ cd pyonfido
$ python setup.py install
```
😶
