### ISSUE TITLE
Upload document in python using onfido library

### ISSUE THREAD

**Issue by varuncanopus** [smcl/pyonfido#9]
Hi,
I am using onfido library to upload a document on onfido in multipart in python but when i tried to upload the document dynamically it is showing 500 internal server error in api.Below is the code of python which will upload the file.

        img_stream = self.request.get ('file')
     self.response.headers['Content-Type'] = 'multipart/form-data'
     img = open(img_stream, "rb")
     applicant_id = 'ef983cad-12e2-430a-a2ac-5f0cac1a13e6'  
     document_file = open(img_stream, "rb")
     document = api.Applicants.doccreate(applicant_id, document_file, "passport.png", 'Passport')

I have find this code from below url it is successfully uploaded the image when we give static name of document in this line

https://documentation.onfido.com/?python#upload-document

document_file = open("passport.png", "rb")

Please help me where i am going wrong

**Comment by hjheath** [comment]
Hi,

Could you post the exact code that hits the error as well as the stack trace of the error you hit?

The `Applicants` class does not have a method called `doccreate`. You need to use `api.Documents.create` to upload a document. Perhaps this is where you are going wrong?

**Comment by varuncanopus** [comment]
yes i have tried with create method also but the result is same.when you 
pass  static file name  it is uploaded successfully on onfido but for dynamic 
uploading of document i used below code but it is showing 500 internal 
server error.so basically my problem is how i can upload a dynamic 
document like browse and upload any file which i want to upload
on onfido using python.for this api.Applicants.create i have created a own
class of Applicant and put all the method of onfido.

code which i write upload dynamic file

class FileHandler(webapp2.RequestHandler):
    def post(self):
        img_stream = self.request.get('file')
        
        filename = self.request.POST["file"].filename
        
        self.response.headers['Content-Type'] = 'multipart/form-data'
        
        check = api.Checks.create("6b1a9350-9df6-4387-a226-7a829226b250", {
        "type": "express",
        "reports": [{ "name": "document" }]
        })
        
        applicant_id = '6b1a9350-9df6-4387-a226-7a829226b250'
        document_file = open(img_stream, "rb")
        document = api.Applicants.create(applicant_id, document_file, img_stream, 'Passport')
   

Please let me know where i am doing wrong.

**Comment by hjheath** [comment]
If you are creating your own Applicants class then this issue is not related to the Python client package and I can't help you. I suggest you do not create your own classes, but use the ones we provide.

You have also contacted tech support and they will help you from here.
